# Sample movie reviews
texts = [
    "I loved this movie, it was amazing!",
    "What a terrible movie, I hated it.",
    "Absolutely fantastic! Would watch again.",
    "Worst movie I have ever seen.",
    "Pretty good film, I enjoyed it.",
    "Awful, do not waste your time.",
    "Excellent acting and great story.",
    "Not great, but not too bad.",
    "I really liked it, a very nice movie.",
    "It was okay, not the best but not bad either.",
    "The plot was engaging and kept me hooked.",
    "Poor script and bad acting ruined it.",
    "Wonderful direction and cinematography.",
    "I fell asleep, completely boring movie.",
    "Amazing soundtrack and visuals.",
    "Terrible editing and confusing storyline.",
    "I would recommend this to my friends.",
    "Do not waste money on this one.",
    "Heartwarming story, loved every moment.",
    "Predictable and dull, very disappointed.",
    "Characters were well developed and relatable.",
    "I disliked the main character, very annoying.",
    "An excellent blend of humor and drama.",
    "Bad pacing and awkward dialogue.",
    "Outstanding performance by the lead actor.",
    "Worst ending I have ever seen.",
    "Loved the chemistry between the actors.",
    "Script was weak and uninteresting.",
    "A masterpiece, brilliant from start to finish.",
    "I could not finish it, extremely boring.",
    "Highly entertaining, great movie night choice.",
    "Terrible movie, do not watch it.",
    "Fantastic visuals and great action scenes.",
    "Awful story, ruined my evening.",
    "Loved the movie, would watch again.",
    "Poorly executed and very confusing plot.",
    "Amazing performance and touching story.",
    "Do not waste your time, very bad movie.",
    "I really enjoyed the film, highly recommend.",
    "Disappointing and forgettable.",
    "Great story, loved every scene.",
    "Awful acting and weak plot.",
    "The movie was engaging and fun.",
    "Terrible direction, very confusing.",
    "Brilliant script and excellent acting.",
    "I hated the film, not recommended.",
    "Wonderful story and superb performances.",
    "Bad movie, save your money.",
    "Excellent drama with emotional depth.",
    "Not worth watching, very boring.",
    "Loved the characters and story.",
    "Poor production, disappointing experience.",
]

# Labels: 1 = Positive, 0 = Negative
labels = [
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
]
